version: "3.5"

services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    user: "${USER_ID}:${USER_ID}"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
    environment:
      PHP_DATE_TIMEZONE: "${TIMEZONE}"
